#!/bin/sh
ls
# try to initiate conda and activate obs environment; else exit
#conda init && conda activate obs || exit

# export environment information without prefix and variables sections
#bash scripts/export_conda_env.sh

# install all files in package directory with pip install
#python -m pip install --editable package
