db_name: obs.db

null_vals: !!python/list [2147483647,-1e+100,"null","NULL","MISSING","XXXX",""," "]

priorities:
  bufr:   0
  synop:  1
  metar:  2

scripts:
  ecdecode.py:
    verbose: 1
    profile: 0
    logging: 0

sources:
  DWD_OpenData:
    dir: DWD
    bufr:
      ext:  bin
      dir:  DWD
      time_keys: !!python/tuple [year, month, day, hour, minute, timePeriod, timeSignificance]
      skip_keys: !!python/tuple [unexpandedDescriptors, timeIncrement]
    synop:
      ext: txt
  KMNI_OpenData:
    dir: KNMI
      ext: bufr
  COD_OpenData:
    dir: COD
    bufr:
      ext: bufr
    synop:
      ext: syn
  RMI_OpenData:
    dir: RMI
    bufr:
      ext: bufr
  NOAA_OpenData:
    dir: NOAA
    bufr:
      ext: bin
    synop:
      ext: txt

station_info: !!python/tuple
  - stationNumber
  - blockNumber
  - stationOrSiteName
  - shortStationName
  - stateIdentifier
  - nationalStationNumber
  - stationType
  - latitude
  - longitude
  - elevation
  - heightOfStationGroundAboveMeanSeaLevel
  - heightOfBarometerAboveMeanSeaLevel
  - heightOfSensorAboveLocalGroundOrDeckOfMarinePlatform
  - heightOfSensorAboveWaterSurface
  - depthBelowWaterSurface
  - depthBelowLandSurface
  - instrumentationForWindMeasurement
  - typeOfInstrumentationForEvaporationMeasurement
  - wigosIdentifierSeries
  - wigosIssuerOfIdentifier
  - wigosIdentifierSeries
  - wigosIssueNumber
  - wigosLocalIdentifierCharacter
  - mainPresentWeatherDetectingSystem
  - supplementaryPresentWeatherSensor
  - visibilityMeasurementSystem
  - cloudDetectionSystem
  - lightningDetectionSensorType
  - skyConditionAlgorithmType
  - capabilityToDetectPrecipitationPhenomena
  - capabilityToDetectOtherWeatherPhenomena
  - capabilityToDetectObscuration
  - capabilityToDiscriminateLightningStrikes
  - methodOfStateOfGroundMeasurement
  - methodOfPrecipitationMeasurement
  - methodOfLiquidContentMeasurementOfPrecipitation
  - methodOfWaterTemperatureAndOrOrSalinityMeasurement
  - methodOfEvaporationMeasurement
  - sensorIndex
