database:
  name: obs.db
  tables: !!python/tuple [station, obs, files]
  table_ext: "sqlite"

priorities:
  bufr:   0
  synop:  1
  metar:  2

scripts:
  get_obs.py: ""
  BUFRdecode.py:
    verbose: 1
    profile: 0
    logging: 0
    min_ram: 1024
    null_vals: [2147483647,-1e+100,"null","NULL","MISSING","XXXX",""," " ]
    time_keys: !!python/tuple [year, month, day, hour, minute, timePeriod, timeSignificance]
    skip_keys: !!python/tuple [unexpandedDescriptors, timeIncrement]
    skip_status: !!python/tuple [parsed, empty, error, locked]
    multi_file: [DWD, NOAA]
  SYNOPdecode.py: ""
  METARdecode.oy: ""

sources:
  DWD:
    bufr:
      ext:  bin
      url:  https://opendata.dwd.de/weather/weather_reports/synoptic/
      wget: "-nc -nd -np -r -l 1 -k -p -H" 
    synop:
      ext:  txt
      url:  https://opendata.dwd.de/weather/weather_reports/synoptic/international/ 
      wget: "-nc -nd -np"
  KNMI:
    bufr:
      ext:  bufr
      #https://developer.dataplatform.knmi.nl/
      url:  https://api.dataplatform.knmi.nl/open-data/v1/datasets/knmi_synop_bufr/versions/1/files 
      api:  eyJvcmciOiI1ZTU1NGUxOTI3NGE5NjAwMDEyYTNlYjEiLCJpZCI6IjA2MTU4MDU3YmM2MDRkMjA5OTExN2ZjOWJkY2IyZThiIiwiaCI6Im11cm11cjEyOCJ9
      curl: "--location --request GET -G {url} -d maxKeys=10 --header Authorization: {api}"
  COD:
    bufr:
      ext:  bufr
      url:  https://weather.cod.edu/digatmos/BUFR/SYNOP/EDZW/
      wget: "-e robots=off -nc -nd -np -r"
    synop:
      ext:  syn
      url:  https://weather.cod.edu/digatmos/syn/
      wget: "-e robots=off -nc -nd -np -r"
  RMI:
    bufr:
      ext:  bufr
      url:  https://opendata.meteo.be/ftp/observations/synop/
      wget: "-nc -nd -np -r"
  NOAA:
    bufr: 
      ext:  bin
      url:  https://tgftp.nws.noaa.gov/SL.us008001/DF.bf/DC.intl/
      wget: "-N -nd -np -r -l 1"
    synop:
      ext:  txt
      url:  https://tgftp.nws.noaa.gov/SL.us008001/DF.an/DC.sflnd/DS.synop/
      wget: "-N -nd -np -r -l 1"
    metar:
      ext:  txt
      url:  ["https://tgftp.nws.noaa.gov/SL.us008001/DF.an/DC.sflnd/DS.metar/", "https://tgftp.nws.noaa.gov/data/observations/metar/stations/"]
      wget: "-N -nd -np -r -l 1"
  #NCAR:
  #  bufr:
  #    ext: bufr
  #    set: https://rda.ucar.edu/datasets/ds461.0/
  #    url: https://data.rda.ucar.edu/ds461.0/bufr/2023/gdas.adpsfc.t00z.20230101.bufr?download=1
  #OGIMET:
  #  bufr:
  #   ext:  [bufr, bin]
  #   url:  http://www.ogimet.com/getbufr.php?res=list&beg=201701290600&end=201701290600 
  #   wget: ""
  #   tar:  true
  #SWISS:
  #  csv:
  #    ext: csv
  #    url: https://data.geo.admin.ch/ch.meteoschweiz.messwerte-aktuell/VQHA98.csv

station_info: !!python/tuple
  - stationNumber
  - blockNumber
  - stationOrSiteName
  - shortStationName
  - stateIdentifier
  - nationalStationNumber
  - stationType
  - latitude
  - longitude
  - elevation
  - heightOfStationGroundAboveMeanSeaLevel
  - heightOfBarometerAboveMeanSeaLevel
  - heightOfSensorAboveLocalGroundOrDeckOfMarinePlatform
  - heightOfSensorAboveWaterSurface
  - depthBelowWaterSurface
  - depthBelowLandSurface
  - instrumentationForWindMeasurement
  - typeOfInstrumentationForEvaporationMeasurement
  - wigosIdentifierSeries
  - wigosIssuerOfIdentifier
  - wigosIdentifierSeries
  - wigosIssueNumber
  - wigosLocalIdentifierCharacter
  - mainPresentWeatherDetectingSystem
  - supplementaryPresentWeatherSensor
  - visibilityMeasurementSystem
  - cloudDetectionSystem
  - lightningDetectionSensorType
  - skyConditionAlgorithmType
  - capabilityToDetectPrecipitationPhenomena
  - capabilityToDetectOtherWeatherPhenomena
  - capabilityToDetectObscuration
  - capabilityToDiscriminateLightningStrikes
  - methodOfStateOfGroundMeasurement
  - methodOfPrecipitationMeasurement
  - methodOfLiquidContentMeasurementOfPrecipitation
  - methodOfWaterTemperatureAndOrOrSalinityMeasurement
  - methodOfEvaporationMeasurement
  - sensorIndex
