CREATE TABLE IF NOT EXISTS station (
  stID varchar PRIMARY KEY,
  updated DATETIME DEFAULT CURRENT_TIMESTAMP,
  stationNumber int unsigned DEFAULT NULL,
  blockNumber int unsigned DEFAULT NULL,
  stationOrSiteName varchar DEFAULT NULL,
  shortStationName varchar DEFAULT NULL,
  stateIdentifier int DEFAULT NULL,
  nationalStationNumber int unsigned DEFAULT NULL,
  stationType int DEFAULT NULL,
  latitude double NOT NULL,
  longitude double NOT NULL,
  elevation int DEFAULT NULL,
  heightOfStationGroundAboveMeanSeaLevel float DEFAULT NULL,
  heightOfBarometerAboveMeanSeaLevel float DEFAULT NULL,
  heightOfSensorAboveLocalGroundOrDeckOfMarinePlatform float DEFAULT NULL,
  heightOfSensorAboveWaterSurface float DEFAULT NULL,
  depthBelowWaterSurface float DEFAULT NULL,
  depthBelowLandSurface float DEFAULT NULL,
  instrumentationForWindMeasurement int DEFAULT NULL,
  typeOfInstrumentationForEvaporationMeasurement int DEFAULT NULL,
  wigosIdentifierSeries int DEFAULT NULL,
  wigosIssuerOfIdentifier int DEFAULT NULL,
  wigosIssueNumber int DEFAULT NULL,
  wigosLocalIdentifierCharacter int DEFAULT NULL,
  surfaceQualifierForTemperatureData int DEFAULT NULL,
  mainPresentWeatherDetectingSystem int DEFAULT NULL,
  supplementaryPresentWeatherSensor int DEFAULT NULL,
  visibilityMeasurementSystem int DEFAULT NULL,
  cloudDetectionSystem int DEFAULT NULL,
  lightningDetectionSensorType int DEFAULT NULL,
  skyConditionAlgorithmType int DEFAULT NULL,
  capabilityToDetectPrecipitationPhenomena int DEFAULT NULL,
  capabilityToDetectOtherWeatherPhenomena int DEFAULT NULL,
  capabilityToDetectObscuration int DEFAULT NULL,
  capabilityToDiscriminateLightningStrikes int DEFAULT NULL,
  methodOfStateOfGroundMeasurement int DEFAULT NULL,
  methodOfPrecipitationMeasurement int DEFAULT NULL,
  methodOfLiquidContentMeasurementOfPrecipitation int DEFAULT NULL,
  methodOfWaterTemperatureAndOrOrSalinityMeasurement int DEFAULT NULL,
  methodOfEvaporationMeasurement int DEFAULT NULL,
  methodOfSnowDepthMeasurement int DEFAULT NULL,
  sensorIndex int DEFAULT NULL
);
