[package]
name = "rust"
version = "0.1.0"
edition = "2021"
build-std = ["core","eccodes","eccodes-sys"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eccodes = "0.10.1"
eccodes-sys = "0.5.2"
