periods:
  WIND_10m_10min_syn:       [10min, ~]
  GUST_10m_10min_syn:       [10min, ~]
  WIND_10m_1h_syn:          [1h,    avg]
  GUST_10m_1h_syn:          [1h,    max]
  MAXWIND_10m_1h_syn:       [1h,    max]
  PRATE_srf_1h_syn:         [1h,    sum]
  PRATE_srf_24h_syn:        [24h,   sum,  6]
  GLRAD_srf_1h_syn:         [1h,    sum]
  LONGRAD_srf_1h_syn:       [1h,    sum]
  DIFFRAD_srf_1h_syn:       [1h,    sum]
  TMIN_5cm_24h_syn:         [24h,   min,  0]
  TMIN_2m_24h_syn:          [24h,   min,  0]
  TMAX_5cm_24h_syn:         [24h,   max,  0]
  TMAX_2m_24h_syn:          [24h,   max,  0]
  TMIN_5cm_12h_syn:         [12h,   min,  18]
  TMIN_2m_12h_syn:          [12h,   min,  18]
  TMAX_5cm_12h_syn:         [12h,   max,  6]
  TMAX_2m_12h_syn:          [12h,   max,  6]
  SUNDUR_srf_1h_syn:        [1h,    sum]
  SUNDUR_srf_24h_syn:       [24h,   sum,  0]
  PCPDUR_srf_1h_syn:        [1h,    sum]
instants:
  TMP_2m_syn:               [10min]
