generalWeatherIndicatorTafOrMetar: # 020009 https://confluence.ecmwf.int/display/ECC/WMO%3D14+element+table#WMO=14elementtable-CL_20
  0:  ~      # RESERVED
  1:  NSC    # NSC MIL SIGNIFICANT CLOUD
  2:  CAVOK  # CAVOK CLOUD AND VISIBILITY OK
  3:  SKC    # SKC SKY CLEAR
  4:  NSW    # NSW NIL SIGNIFICANT WEATHER
  15: ~      # MISSING VALUE


verticalSignificanceSurfaceObservations: # 008002 https://confluence.ecmwf.int/display/ECC/WMO%3D14+element+table#WMO=14elementtable-CL_8
  0:  0 # Observing rules for base of lowest cloud and cloud types of FM 12 SYNOP and FM 13 SHIP apply
  1:  1 # First non-Cumulonimbus significant layer
  2:  2 # Second non-Cumulonimbus significant layer
  3:  3 # Third non-Cumulonimbus significant layer
  4:  4 # Cumulonimbus layer
  5:  C # Ceiling
  6:  0 # Clouds not detected below the following height(s)
  7:  L # Low cloud
  8:  M # Middle cloud
  9:  H # High cloud
  10: 0 # Cloud layer with base below and top above the station
  11: 0 # Cloud layer with base and top below the station level
  21: 1 # First instrument detected cloud layer
  22: 2 # Second instrument detected cloud layer
  23: 3 # Third instrument detected cloud layer
  24: 4 # Fourth instrument detected cloud layer
  62: 0 # Value not applicable
  63: 0 # Missing value


cloudType:  # 020012 https://confluence.ecmwf.int/display/ECC/WMO%3D14+element+table#WMO=14elementtable-CL_20
  0:  Ci  # CIRRUS (CI)...............CI
  1:  Cc  # CIRROCUMULUS (CC).........CC
  2:  Cs  # CIRROSTRATUS (CS).........CS
  3:  Ac  # ALTOCUMULUS (AC)..........AC
  4:  As  # ALTOSTRATUS (AS)..........AS
  5:  Ns  # NIMBOSTRATUS (NS).........NS
  6:  Sc  # STRATOCUMULUS(SC).........SC
  7:  St  # STRATUS (ST)..............ST
  8:  Cu  # CUMULUS (CU)..............CU
  9:  Cb  # CUMULONIMBUS (CB).........CB
  10: //  # NO CH CLOUDS
  11: Ci  # CIRRUS FIBRATUS, SOMETIMES UNCINUS, NOT PROGRESSIVELY INADING THE SKY
  12: Ci  # CIRRUS SPISSATUS, IN PATCHES OR ENTANGLED SHEAVES, WHICH USUALLY DO NOT INCREASE AND SOMETIMES SEEM TO BE THE REMAINS OF THE UPPER PART OF AN ANVIL
  13: Ci  # CIRRUS SPISSATUS CUMULONIMBOGENITUS
  14: Ci  # CIRRUS UNCINUS OR FIBRATUS, OR BOTH, PROGRESSIVELY INVADING THE SKY; THEY GENERALLY THICKEN AS A WHOLE
  15: Cs  # CIRRUS (OFTEN IN BANDS) AND CIRROSTRATUS, OR CIRROSTRATUS AL ONE, PROGRESSIVELY INVADING THE SKY; THEY GENERALLY THICKEN AS A WHOLE
  16: Cs  # CIRRUS (OFTEN IN BANDS) AND CIRROSTRATUS, OR CIRROSTRATUS AL ONE, PROGRESSIVELY INVADING THE SKY; THEY GENERALLY THICKEN AS A WHOLE
  17: Cs  # CIRROSTRATUS COVERING THE WHOLE SKY
  18: Cs  # CIRROSTRATUS NOT PROGRESSIVELY INVADING THE SKY AND NOT ENTIRELY COVERING IT
  19: Cc  # CIRROCUMULUS ALONE, OR CIRROCUMULUS PREDOMINANT AMONG THE CH CLOUDS
  20: /   # NO CM CLOUDS
  21: As  # ALTOSTRATUS TRANSLUCIDUS
  22: Ns  # ALTOSTRATUS OPACUS OR NIMBOSTRATUS
  23: Ac  # ALTOCUMULUS TRANSLUCIDUS AT A SINGLE LEVEL
  24: Ac  # PATCHES (OFTEN LENTICULARIS) OF ALTOCUMULUS TRANSLUCIDUS, CONTINUALLY CHANGING AND OCCURING AT ONE OR MORE LEVELS
  25: Ac  # ALTOCUMULUS TRANSLUCIDUS IN BANDS, OR ONE OR MORE LAYERS OF ALTOCUMULUS TRANSLUCIDUS OR OPACUS, PROGRESSIVELY INVADING THE SKY
  26: Ac  # ALTOCUMULUS CUMULOGENITUS (OR CUMULONIMBOGENITUS)
  27: Ac  # ALTOCUMULUS TRANSLUCIDUS OR OPACUS IN TWO OR MORE LAYERS, OR ALTOCUMULUS OPACUS IN A SINGLE LAYER, NOT PROGRESSIVELY INVADING THE SKY
  28: Ac  # ALTOCUMULUS CASTELLANUS OR FLOCUS
  29: Ac  # ALTOCUMULUS OF CHAOTIC SKY, GENERALLY AT SEVERAL LEVELS
  30: //  # NO CL CLOUDS
  31: Cu  # CUMULUS HUMILIS OR CUMULUS FRACTUS OTHER THAN OF BAD WEATHER, OR BOTH
  32: Cu  # CUMULUS MEDIOCRIS OR CONGESTUS, WITH OR WITHOUT CUMULUS OF SPECIES FRACTUS OR HUMULIS OR STRATOCUMULUS, ALL HAVING THEIR BASES AT THE SAME LEVEL
  33: Cb  # CUMULONIMBUS CALVUS, WITH OR WITHOUT CUMULUS, STRATOCUMULUS OR STRATUS
  34: Sc  # STRATOCUMULUS CUMULOGENITUS
  35: Sc  # STRATOCUMULUS OTHER THAN STRATOCUMULUS CUMULOGENITUS
  36: St  # STRATUS NEBULOSUS OR STRATUS FRACTUS OTHER THAN OF BAD WEATH" ER, OR BOTH
  37: Cu  # STRATUS FRACTUS OR CUMULUS FRACTUS OF BAD WEATHER, OR BOTH (PANNUS), USUALLY BELOW ALTOSTRATUS OR NIMBOSTRATUS
  38: Cu  # CUMULUS AND STRATOCUMULUS OTHER THAN STRATOCUMULUS CUMULOGENITUS, WITH BASES AT DIFFERENT LEVELS
  39: Cb  # CUMULONIMBUS CAPILLATUS (OFTEN WITH AN ANVIL), WITH OR WITHOUT CUMULONIMBUS CALVUS, CUMULUS, STRATOCUMULUS, STRATUS OR PANNUS
  59: //
  60: //
  61: //
  62: //
  63: //
