### UNIT CONVERSIONS
# excact-as-possible unit conversion factors
# great source for these fractions: https://unitchefs.com/speed/

# TEMPERATURE
K2C:   &K2C    -273.15             # K to C
#C2K:   &C2K    273.15              # C to K

# WIND SPEED
kn2ms:  &kn2ms  0.5144444444444445  # kn to m/s
ms2kn:  &ms2kn  1.9438444924406046  # m/s to kn
kh2kn:  &kh2kn  0.5399568034557235  # km/h to kn
kh2ms:  &kh2ms  0.2777777777777778  # km/h in m/s

# LENGTH
#m2ft:   &m2ft   3.2808398950131235  # m to ft
#ft2m:   &ft2m   0.3048
m2m30:  &m2m30  0.03333333333333333 # m  to m/30 
ft2m30: &ft2m30 0.01016             # ft to m/30

# helper key, not part of BUFR tables
cloudBase:
  1:                                [CB1_2m_syn,     1s, 1, 0]
  2:                                [CB2_2m_syn,     1s, 1, 0]
  3:                                [CB3_2m_syn,     1s, 1, 0]
  4:                                [CB4_2m_syn,     1s, 1, 0]
  #TODO see obs.cfg for cloud level thresholds

timePeriod:
  0:      0s
  -1:     1h  # we need to skip all 1 min obs (weather and precipitation) to savely assume this
  -3:     3h
  -6:     6h
  -10:    10min
  -12:    12h
  -15:    15h
  -24:    24h
  -25:    25h
  -30:    30min # TODO does this overlap with 30h sometimes???
  -36:    36h
  -60:    1h
  -180:   3h
  -360:   6h
  -720:   12h
  -900:   15h
  -1440:  24h
  -1500:  25h
  -1800:  30h
  -2160:  36h

  ### EXTRA HELPER PARAMETERS
  #TODO use for derived paramters during decoding or remove -> derive_obs.py
  #relativeHumidity:                   [RH_2m_syn,  1s, 1,     0]
  #wetBulbTemperature:
  #  0.05:                             [WBT_5cm_syn, 1s, 1, *K2C]
  #  2.0:                              [WBT_2m_syn,  1s, 1, *K2C]
  #wetBulbTemperatureAt2M:             [WBT_2m_syn,  1s, 1, *K2C]
  #virtualTemperature:
  #  0.05:                             [VT_5cm_syn, 1s,  1, *K2C]
  #  2.0:                              [VT_2m_syn,  1s,  1, *K2C]
  #specificHumidity:                   [SH_2m_syn,  1s,  1,    0]
  #mixingRatio:                        [MR_2m_syn,  1s,  1,    0]
  #mixingHeights:                      [MH_syn,     1s,  1,    0]
  #vapourPressure:                     [VP_2m_syn,  1s,  1,    0]
  #vapourDensity:                      [VD_2m_syn,  1s,  1,    0]

  #TODO apparently not present in DWD BUFRs but could be useful for other data sources in future...
  #representativeHeightOfSensorAboveStation:            ~
  #modificationOfSensorHeightToAnotherValue:            ~
  #heightOfSensorAboveWaterSurface:                     ~
  #nonCoordinateHeight:                                 ~

### SNOW
#TODO units/scale
totalSnowDepth:                     [SNOD_srf_syn, 1s, 100, 0]   # Gesamtschneehöhe [in cm]
depthOfFreshSnow:                   [NEWSNOD_srf_syn,  ~, 100, 0]   # Neuschneehöhe [in cm] im Bezugszeitraum

### PRECIPITATION
#TODO units/scale
totalPrecipitationOrTotalWaterEquivalent: [PRATE_1m_syn, ~,    1, 0] # Niederschlagsmenge
totalPrecipitationPast1Hour:              [PRATE_1m_syn, 1h,   1, 0]
totalPrecipitationPast3Hours:             [PRATE_1m_syn, 3h,   1, 0]
totalPrecipitationPast6Hours:             [PRATE_1m_syn, 6h,   1, 0]
totalPrecipitationPast12Hours:            [PRATE_1m_syn, 12h,  1, 0]
totalPrecipitationPast24Hours:            [PRATE_1m_syn, 24h,  1, 0] # Niederschlagsmenge der letzten 24 Stunden
totalAccumulatedPrecipitation:            [PRATE_1m_syn, ~,    1, 0] # Niederschlagsmenge im Bezugszeitraum
durationOfPrecipitation:                  [PCPDUR_1m_syn,  ~,   1, 0]
  #TODO precipitation could also be derived from duration + intensity
  #intensityOfPrecipitation:              [PCPINT_1m_syn, ~,    1, 0]
  #highestDailyAmountOfPrecipitation:     [PCPMAX_1m_syn, 24h,  1, 0]
  #TODO might be useful if WW is missing?
  #typeOfPrecipitation:                   [PCPTYPE_1m_syn, ~, 1, 0]
  #formOfPrecipitation:                   [PCPFORM_1m_syn, ~, 1, 0]

### PRESSURE
pressure:                           [PRES_0m_syn,   1s, 0.01,   0]      # Luftdruck an der Station
nonCoordinatePressure:              [PRES_0m_syn,   1s, 0.01,   0]      # Luftdruck an der Station
pressureReducedToMeanSeaLevel:      [PRMSL_ms_syn,  1s, 0.01,   0]      # Auf NN reduzierter Luftdruck TODO QFF/QNH?!

### RADIATION / SUN
globalSolarRadiationIntegratedOverPeriodSpecified:  [GLRAD_srf_syn,   ~,    0.001, 0] # Globalstrahlung
globalSolarRadiation24Hours:                        [GLRAD_srf_syn,   24h,  0.001, 0]
globalSolarRadiationIntegratedOver24Hours:          [GLRAD_srf_syn,   24h,  0.001, 0]
longWaveRadiationIntegratedOverPeriodSpecified:     [LONGRAD_srf_syn, ~,    0.001, 0] # Langwellige Strahlung
longWaveRadiationIntegratedOver24Hours:             [LONGRAD_srf_syn, 24h,  0.001, 0] # Langwellige Strahlung
#TODO is net really the same as above?
netLongWaveRadiationIntegratedOverPeriodSpecified:  [LONGRAD_srf_syn, ~,    0.001, 0] # Langwellige Strahlung
netLongWaveRadiationIntegratedOver24Hours:          [LONGRAD_srf_syn, 24h,  0.001, 0] # Langwellige Strahlung
diffuseSolarRadiationIntegratedOverPeriodSpecified: [DIFFRAD_srf_syn, ~,    0.001, 0] # Diffusstrahlung
diffuseSolarRadiationIntegratedOver24Hours:         [DIFFRAD_srf_syn, 24h,  0.001, 0] # Diffusstrahlung
totalSunshine:                      [SUNDUR_srf_syn, ~, 1,  0]      # Sonnenscheindauer am Vortag oder 1h 
sunshineOverPeriodSpecified:        [SUNDUR_srf_syn, ~, 1,  0]      # Sonnenscheindauer im Bezugszeitraum

### WEATHER / PHENOMENA
presentWeather:                     [WW_2m_syn,  1min, 1, 0]           # Signifikantes Wetter
  #TODO these keys contain characters (CCITT IA5 code), useful?
  #significantWeather:                 [WWsig_2m_syn,1min, 1, 0]         # Signifikantes Wetter
  #significantRecentWeatherPhenomena:  [WWsig_2n_syn,1min, 1, 0]         # Signifikantes Wetter
pastWeather1:                       [W1_2m_syn,  ~,    1, 0]           # Wetterverlauf (Typ 1)
pastWeather2:                       [W2_2m_syn,  ~,    1, 0]           # Wetterverlauf (Typ 2)
  #additionalWeatherPhenomena:         [natWW_2m_syn,   1min, 1, 0]           # Zusätzliches Wetter (Nationale Meldung)
  #TODO some interesting BUFR keys, maybe with potential future usefulness?
  #intensityOfPhenomena:               [PHint_2m_syn, ~, 1, 0]              #
  #phenomenaOccurrence:                [PHocc_2m_syn, ~, 1, 0]              # 
  #specialPhenomena:                   [PHspl_2m_syn, ~, 1, 0]              # 
  #otherWeatherPhenomena:              [PHoth_2m_syn, ~, 1, 0]              # 
#this parameter is not equivalent to metwatch METAR parameter (WW_2m_met), does not contain specific significant weather information (like RA, TS or DZ)
generalWeatherIndicatorTafOrMetar:      [GWI_2m_met, 1min, 1, 0]           # Signifikantes Wetter und Bewölkung

### VISIBILITY
#TODO which of these visibility/optical range parameters should have priority? how do we order them?
meteorologicalOpticalRange:             [VIS_2m_syn,     0s, 0.001, 0] # Horizontale Sichtweite
minimumMeteorologicalOpticalRange:      [VISmin_2m_syn,  0s, 0.001, 0] # minimale Horizontale Sichtweite
maximumMeteorologicalOpticalRange:      [VISmax_2m_syn,  0s, 0.001, 0] # maximale Horizontale Sichtweite
horizontalVisibility:                   [VIS_2m_syn,     0s, 0.001, 0] # Horizontale Sichtweite
minimumHorizontalVisibility:            [VISmin_2m_syn,  0s, 0.001, 0] # minimale Horizontale Sichtweite
prevailingHorizontalVisibility:         [VISpre_2m_syn,  0s, 0.001, 0] # vorherrschende Horizontale Sichtweite
runwayVisualRangeRvr:                   [VIS_2m_met,    0s, 0.001, 0] # Horizontale Sichtweite auf dem Rollfeld
visibilitySeawardsFromACoastalStation:  [VISsea_2m_syn,  0s, 0.001, 0] # Horizontale Sichtweite (Küste Richtung See)

### TEMPERATURE / GROUND
stateOfGround:                      [GS_srf_syn,    1min,  1,    0]     # Erdbodenzustand
soilTemperature:
  -0.05:                            [TMP_n5cm_syn,  1s, 1, *K2C]     # Erdbodentemperatur -5cm
  -0.1:                             [TMP_n10cm_syn, 1s, 1, *K2C]     # Erdbodentemperatur -10cm
  -0.2:                             [TMP_n20cm_syn, 1s, 1, *K2C]     # Erdbodentemperatur -20cm
  -0.5:                             [TMP_n50cm_syn, 1s, 1, *K2C]     # Erdbodentemperatur -50cm
  -1.0:                             [TMP_n1m_syn,   1s, 1, *K2C]     # Erdbodentemperatur -1m
  -2.0:                             [TMP_n2m_syn,   1s, 1, *K2C]     # Erdbodentemperatur -2m
groundTemperature:                  [TMP_srf_syn,   1s, 1, *K2C]     # Erdbodentemperatur 0cm
  #TODO interesting parameters
  #groundMinimumTemperature
  #groundMinimumTemperatureOfPrecedingNight
  #groundMinimumTemperaturePast12Hours

  #TODO could be useful for other data sources than DWD
  #principalTimeOfDailyReadingInUtcOfMaximumTemperature: ~
  #principalTimeOfDailyReadingInUtcOfMinimumTemperature: ~
  #timeDifference:                                       ~
  #hoursIncluded:                                        ~
  #measurementIntegrationTime:                           ~
  #durationOfTimeRelatingToFollowingValue:

temperature: # in Celsius! 
  0.05:                             [TMP_5cm_syn,     1s, 1, 0]      # 5cm-Lufttemperatur
  2.0:                              [TMP_2m_syn,      1s, 1, 0]      # 2m-Lufttemperatur
airTemperature:                     
  0.05:                             [TMP_5cm_syn,     1s, 1, *K2C]   # 5cm-Lufttemperatur
  2.0:                              [TMP_2m_syn,      1s, 1, *K2C]   # 2m-Lufttemperatur
airTemperatureAt2M:                 [TMP_2m_syn,      1s, 1, *K2C]   # 2m-Lufttemperatur   
dewpointTemperature:
  0.05:                             [DPT_5cm_syn,    1s, 1, *K2C]   # 5cm-Taupunktstemperatur
  2.0:                              [DPT_2m_syn,     1s, 1, *K2C]   # 2m-Taupunktstemperatur
dewpointTemperatureAt2M:            [DPT_2m_syn,     1s, 1, *K2C]   # 2m-Taupunktstemperatur

maximumTemperatureAt2M:             [TMAX_2m_syn,   12h,  1, *K2C] # 24h-Maximum der 2m-Lufttemperatur
minimumTemperatureAt2M:             [TMIN_2m_syn,   12h,  1, *K2C] # 24h-Minimum der 2m-Lufttemperatur
maximumTemperatureAtHeightAndOverPeriodSpecified:
  0.05:                             [TMAX_5cm_syn,  12h,  1, *K2C] # 24h-Maximum der 5cm-Lufttemperatur
  2.0:                              [TMAX_2m_syn,   12h,  1, *K2C] # 24h-Maximum der 2m-Lufttemperatur
minimumTemperatureAtHeightAndOverPeriodsPecified:
  0.05:                             [TMIN_5cm_syn,  12h,  1, *K2C] # 24h-Minimum der 5cm-Lufttemperatur
  2.0:                              [TMIN_2m_syn,   12h,  1, *K2C] # 24h-Minimum der 2m-Lufttemperatur
maximumTemperatureAt2MPast12Hours:  [TMAX_2m_syn,   12h,  1, *K2C]
minimumTemperatureAt2MPast12Hours:  [TMIN_2m_syn,   12h,  1, *K2C]
maximumTemperatureAt2MPast24Hours:  [TMAX_2m_syn,   24h,  1, *K2C]
minimumTemperatureAt2MPast24Hours:  [TMIN_2m_syn,   24h,  1, *K2C]
maximumTemperatureAtHeightSpecifiedPast24Hours:
  0.05:                             [TMAX_5cm_syn,  24h,  1, *K2C]
  2.0:                              [TMAX_2m_syn,   24h,  1, *K2C]
minimumTemperatureAtHeightSpecifiedPast24Hours:
  0.05:                             [TMIN_5cm_syn,  24h,  1, *K2C]
  2.0:                              [TMIN_2m_syn,   24h,  1, *K2C]

oceanographicWaterTemperature:      [Twater_sst_syn, 1s, 1,  *K2C] # Wassertemperatur sea surface temperature


### WIND
u:                                  [u_10m_syn, ~, 1, 0]
uAt10M:                             [u_10m_syn, ~, 1, 0]
v:                                  [v_10m_syn, ~, 1, 0]
vAt10M:                             [v_10m_syn, ~, 1, 0]

  #TODO how/where is the associated wind speed defined?
  #windDirectionAssociatedWithWindSpeedWhichFollows:                 [DIR_10m_syn, ~, 1, 0]
windDirection:                      [WDIR_10m_syn, 10min, 1, 0]       # Windrichtung
windDirectionAt10M:                 [WDIR_10m_syn, 10min, 1, 0]       # Windrichtung
windDirectionAt5M:                  [WDIR_5m_syn, 10min, 1, 0]        # Windrichtung
  #maximumWindGustDirection:           [WDIRmax_10m_syn, ~, 1, 0, 0]     # Windrichtung der max Böen
windSpeed:                          [WIND_10m_syn, 10min, 1, 0]  # Windgeschwindigkeit 10-Min-Mittel kn
windSpeedAt10M:                     [WIND_10m_syn, 10min, 1, 0]  # Mittelwind der letzten Stunde
windSpeedAt5M:                      [WIND_5m_syn, 10min, 1, 0]   # Mittelwind der letzten Stunde
meanWindSpeed:                      [WIND_10m_syn, 10min, 1, 0]
  #TODO rename to MAXWIND?
maximumMeanWindSpeed:               [MAXWIND_10m_syn,~, 1,  0]
  #TODO rename to MINWIND?
  #minimumMeanWindSpeed:               [WINDmin_10m_syn,~, 1,  0]
highestGustDuringThe10MinutePeriodPrecedingObservation: [GUST_10m_syn, 10min, 1, 0]
meanWindSpeedFrom610minMeasurement: [WIND_10m_syn,    1h, 1, 0] # Windgeschwindigkeit 10-Min-Mittel kn
maximumWindGustSpeed:               [GUST_10m_syn,     ~, 1, 0]
maximumWindSpeed10MinuteMeanWind:   [MAXWIND_10m_syn, ~, 1, 0] # Maximales 10min-Mittel im Bezugszeitraum
  #TODO what are these? how is their duration defined? Different from gust speeds or equal/comparable?
  #maximumInstantaneousWindSpeed:      [FFmax_10m_syn, ~,  1, 0]
  #maximumInstantaneousWindSpeedOver10Minutes:  [FFmax_10m_syn, 10min, 1, 0]

### CLOUDS
  #TODO could these keys be useful in future?
  #cloudIndex:                              [CDindex_syn, 1s, 1,   0]
  #verticalSignificanceSurfaceObservations: [VERTSIG_surf_syn, 1s, 1, 0]
  
  #TODO implement in derive_obs.py
  #ClNCmNChN: [CLCMCH_syn,  ~, 1, 0]  # Wolkenarten in den Stockwerken                   (zB: Cu3Ac4Cs51Cb, 1Cu)
  #ClNCmNChN: [CLCMCH_syn,  ~, 1, 0]  # -> Wolkenmenegen in den Stockwerken              (zB: 3451, 1///)
  #NC1XXX:    [CL1_syn,     ~, 1, 0]  # unterste Wolkenschicht Bedeckung/Art/Untergrenze (zB: 2ST020 oder OBS///)
  #NC2XXX:    [CL2_syn,     ~, 1, 0]  # 2.Wolkenschicht                                  (zB: 4AC100)
  #NC3XXX:    [CL3_syn,     ~, 1, 0]  # 3.Wolkenschicht                                  (zB: 5CS300)
  #NC4XXX:    [CL4_syn,     ~, 1, 0]  # 4.Wolkenschicht                                  (zB: 2CB080)
  #NC1XXX:    [CL?_syn,     ~, 1, 0]  # Wolkenschicht Bedeckung+Untergrenze              (zB: 2020, 5300, 2080)

cloudAmount:
  0:                                [TCDC_2m_syn,   1s,   1,  0]    # Bedeckungsgrad gesamt
  C:                                [LCDC_2m_syn,   1s,   1,  0]    # Bedeckungsgrad der niedrigsten Schicht (DWD meldet immer 9) TODO rename "NCDC" or "CCDC" (for Nh/ceiling)
  L:                                [CDCL_2m_syn,   1s,   1,  0]    # Bedeckungsgrad der niedrigen Wolken
  M:                                [CDCM_2m_syn,   1s,   1,  0]    # Bedeckungsgrad der mitteleren Wolken
  H:                                [CDCH_2m_syn,   1s,   1,  0]    # Bedeckungsgrad der hohen Wolken
  1:                                [CDC1_2m_syn,   1s,   1,  0]    # Bedeckungsgrad 1. Schicht
  2:                                [CDC2_2m_syn,   1s,   1,  0]    # Bedeckungsgrad 2. Schicht
  3:                                [CDC3_2m_syn,   1s,   1,  0]    # Bedeckungsgrad 3. Schicht
  4:                                [CDC4_2m_syn,   1s,   1,  0]    # Bedeckungsgrad 4. Schicht (Cb oder 4. Automat)

cloudCoverTotal:                    [TCDC_2m_syn, 1s, 0.08, 0]    # Bedeckungsgrad gesamt

heightOfBaseOfCloud:                [HLC_2m_syn,       1s,1, 0]   # Höhe der tiefen Wolken (tiefste Wolkenschicht)

# usually not used by DWD
amountOfLowClouds:                  [CDCL_2m_syn,    1s,   1,   0]   # Bedeckungsgrad der niedrigen Wolken
amountOfMiddleClouds:               [CDCM_2m_syn,    1s,   1,   0]   # Bedeckungsgrad der mitteleren Wolken
amountOfHighClouds:                 [CDCH_2m_syn,    1s,   1,   0]   # Bedeckungsgrad der hohen Wolken
