#element              | min             | max           | extra             | excluded|
#---------------------+-----------------+---------------+-------------------+---------+
WDIR_10m_syn:         [    0,             360,            [990],              ~       ]
WIND10min_10m_syn:    [    0,             150,            [0],                ~       ]
WIND30min_10m_syn:    [    0,             150,            [0],                ~       ]
WIND1h_10m_syn:       [    0,             150,            [0],                ~       ]
GUST10min_10m_syn:    [    0,             200,            [0],                ~       ]
GUST30min_10m_syn:    [    0,             200,            [0],                ~       ]
GUST1h_10m_syn:       [    0,             200,            [0],                ~       ]
GUST6h_10m_syn:       [    0,             200,            [0],                ~       ]
MAXWIND10min_10m_syn: [    0,             180,            [0],                ~       ] 
MAXWIND30min_10m_syn: [    0,             180,            [0],                ~       ]
MAXWIND1h_10m_syn:    [    0,             180,            [0],                ~       ]

TMP_2m_syn:           [ -700,             600,            [0],                ~       ]
DPT_2m_syn:           [ -800,             600,            [0],                ~       ] 
TMP_5cm_syn:          [ -700,             600,            [0],                ~       ]

Tmax12h_2m_syn:       [ -700,             600,            [0],                ~       ]
Tmin12h_2m_syn:       [ -700,             400,            [0],                ~       ]
Tmin12h_5cm_syn:      [ -700,             400,            [0],                ~       ]
Tmax24h_2m_syn:       [ -700,             600,            [0],                ~       ]
Tmin24h_2m_syn:       [ -700,             400,            [0],                ~       ]
Tmin24h_5cm_syn:      [ -700,             400,            [0],                ~       ]

Twater_sst_syn:       [  -30,             400,            [0],                ~       ]
TMP_srf_syn:          [ -600,             600,            [0],                ~       ]
TMP_n5cm_syn:         [ -600,             600,            [0],                ~       ]
TMP_n10cm_syn:        [ -600,             600,            [0],                ~       ]
TMP_n20cm_syn:        [ -600,             600,            [0],                ~       ]
TMP_n50cm_syn:        [ -600,             600,            [0],                ~       ]
TMP_n1m_syn:          [ -600,             600,            [0],                ~       ]
TMP_n2m_syn:          [ -600,             600,            [0],                ~       ]

PRES_0m_syn:          [  700,            1080,            [0],                ~       ]
PRMSL_ms_syn:         [  920,            1070,            [0],                ~       ]
PRMSLNN_ms_met:       [  920,            1070,            [0],                ~       ]

GS_syn:               [    0,              19,            [31],               ~       ]

WW_syn:               [    0,             293,            [508,509,510,511],  "3%"    ]
WWN_met:              [    0,               5,            [15],               3       ]
W1_syn:               [    0,              19,            [31],               ~       ]
W2_syn:               [    0,              19,            [31],               3       ]
  #natWW:                [    0,               4,            [7,8,9,33,36],      3       ]
VIS_syn:              [    0,             999,            [0],                ~       ]

TCDC_2m_syn:          [    0,               9,            [0],                ~       ]
LCDC_2m_syn:          [    0,               9,            [0],                ~       ]
MCDC_2m_syn:          [    0,               9,            [0],                ~       ]
HCDC_2m_syn:          [    0,               9,            [0],                ~       ]
HLC_syn:              [    0,               0,            [0],                ~       ]
CLCMCH_syn:           [    0,               0,            [0],                ~       ]
CL1_syn:              [    0,               0,            [9],                ~       ]
CL2_syn:              [    0,               0,            [9],                ~       ]
CL3_syn:              [    0,               0,            [9],                ~       ]
CL4_syn:              [    0,               0,            [9],                ~       ]

PRATE30min_1m_syn:    [    0,             300,            [0],                ~       ]
PRATE1h_1m_syn:       [    0,             600,            [0],                ~       ]
PRATE24h_1m_syn:      [    0,           14400,            [0],                ~       ]
PCPDUR30min_srf_syn:  [    0,              30,            [0],                ~       ]
PCPDUR1h_srf_syn:     [    0,              60,            [0],                ~       ]

SNOD_srf_syn:         [    0,            1000,            [0],                ~       ]
NEWSNOD1h_srf_syn:    [    0,              10,            [0],                ~       ]
NEWSNOD24h_srf_syn:   [    0,             240,            [0],                ~       ] 

SUNDUR30min_srf_syn:  [    0,              30,            [0],                ~       ]
SUNDUR1h_srf_syn:     [    0,              60,            [0],                ~       ]
SUNDUR24h_srf_syn:    [    0,            1440,            [0],                ~       ]
GLRAD30min_srf_syn:   [    0,             500,            [0],                ~       ]
GLRAD1h_srf_syn:      [    0,            1000,            [0],                ~       ]
DIFFRAD30min_srf_syn: [    0,             500,            [0],                ~       ]
DIFFRAD1h_srf_syn:    [    0,            1000,            [0],                ~       ]
LONGRAD30min_srf_syn: [    0,             500,            [0],                ~       ]
LONGRAD1h_srf_syn:    [    0,            1000,            [0],                ~       ]


#TODO proposals:
#rename MAXGUST to MAXWIND (because it the max mean wind speed, not an actual gust)
#(srf, 0m, ms, sst) -> 0m OR srf
#remove suffixes syn and met!
#add suffix with height infos to params like HLC, GS, WW, W1, W2 and natWW (where it is missing)
#no seperate duration column after aggregation step; duration always after param name!
