duration:
  WIND_10m_syn:
    #TODO use WIND_5m_syn as fallback element?
    10min:                  ~
    30min:                  [[10min],                         AVG]
    1h:                     [[30min, 10min],                  AVG]
  GUST_10m_syn:
    30min:                  [[10min],                         MAX]
    1h:                     [[30min, 10min],                  MAX]
    6h:                     [[3h, 1h, 30min, 10min],          MAX]
  MAXWIND_10m_syn:
    #TODO implement fallback element WIND_10m_syn
    30min:                  [[10min],                         MAX]
    1h:                     [[30min, 10min],                  MAX]
    6h:                     [[3h, 1h, 30min, 10min],          MAX, WIND_10m_syn, 0  ]
  PRATE_srf_syn:
    30min:                  [[10min],                         SUM]
    1h:                     [[1h, 30min, 10min],              SUM]
    24h:                    [[12h, 6h, 3h, 1h, 30min, 10min], SUM]
  PCPDUR_srf_syn:
    30min:                  [[10min],                         SUM]
    1h:                     [[30min, 10min],                  SUM]
  PCPINT_srf_syn:
    30min:                  [[10min],                         MAX]
    1h:                     [[30min, 10min],                  MAX]
  SUNDUR_srf_syn:
    30min:                  [[10min],                         SUM]
    1h:                     [[30min, 10min],                  SUM]
    24h:                    [[12h, 6h, 3h, 1h, 30min, 10min], SUM]
  GLRAD_srf_syn:
    30min:                  [[10min],                         SUM]
    1h:                     [[30min, 10min],                  SUM]
  LONGRAD_srf_syn:
    30min:                  [[10min],                         SUM]
    1h:                     [[30min, 10min],                  SUM]
  DIFFRAD_srf_syn:
    30min:                  [[10min],                         SUM]
    1h:                     [[30min, 10min],                  SUM]
  NEWSNOD_srf_syn:
    1h:                     [[30min, 10min],                  SUM]
    24h:                    [[12h, 6h, 3h, 1h, 30min, 10min], SUM]
  TMIN_5cm_syn:
    #TODO implement fallback element TMP_5cm_syn
    12h:                    [[12h, 6h, 3h, 1h],               MIN, TMP_5cm_syn, -6  ]
    24h:                    [[24h, 12h, 6h, 3h, 1h],          MIN, TMP_5cm_syn, 0   ]
  TMIN_2m_syn:
    #TODO implement fallback element TMP_2m_syn
    12h:                    [[12h, 6h, 3h, 1h],               MIN, TMP_2m_syn,  -6  ]
    24h:                    [[24h, 12h, 6h, 3h, 1h],          MIN, TMP_2m_syn,  0   ]
  TMAX_2m_syn:
    #TODO implement fallback element TMP_2m_syn
    12h:                    [[12h, 6h, 3h, 1h],               MAX, TMP_2m_syn,  6   ]
    24h:                    [[24h, 12h, 6h, 3h, 1h],          MAX, TMP_2m_syn,  0   ]

instant:
  # instantaneous / fixed duration values
  # if not available on full hour/30mins?, look for close-by values [+-, 10, min]
  - WDIR_10m_syn # always 10-min average
  - TMP_2m_syn
  - DPT_2m_syn
  - TMP_5cm_syn
  - Twater_sst_syn
  - TMP_srf_syn
  - TMP_n5cm_syn
  - TMP_n10cm_syn
  - TMP_n20cm_syn
  - TMP_n50cm_syn
  - TMP_n1m_syn
  - TMP_n2m_syn
  - PRES_0m_syn
  - PRMSL_ms_syn 
  - PRMSL_ms_met
  - WW_2m_syn 
  - WWN_2m_met
  - W1_2m_syn
  - W2_2m_syn
  - natWW_2n_syn
  - VIS_2m_syn
  - TCDC_2m_syn
  - LCDC_2m_syn
  - HLC_2m_syn
  - CB1_2m_syn
  - CB2_2m_syn
  - CB3_2m_syn
  - CB4_2m_syn
  - SNOD_srf_syn
  - GS_srf_syn
