#element              | min             | max           | extra   | excluded
WDIR_5m_syn:          [    0,             360,            990,      ~   ]
WDIR_10m_syn:         [    0,             360,            990,      ~   ]
WIND_5m_syn:          [    0,             360,            990,      ~   ]
WIND_10m_syn:         [    0,             150,            0,        ~   ]
GUST_10m_syn:         [    0,             200,            0,        ~   ]
MAXGUST_10m_syn:      [    0,             180,            0,        ~   ]
TMP_2m_syn:           [ -700,             600,            0,        ~   ]
DPT_2m_syn:           [ -800,             600,            0,        ~   ] 
TMP_5cm_syn:          [ -700,             600,            0,        ~   ]
Tmax_2m_syn:          [ -700,             600,            0,        ~   ]
Tmin_2m_syn:          [ -700,             400,            0,        ~   ]
Tmax_5cm_syn:         [ -700,             600,            0,        ~   ]
Tmin_5cm_syn:         [ -700,             400,            0,        ~   ]
Twater_sst_syn:       [  -30,             400,            0,        ~   ]
TMPT_srf_syn:         [ -600,             600,            0,        ~   ]
TMP_n5cm_syn:         [ -600,             600,            0,        ~   ]
TMP_n10cm_syn:        [ -600,             600,            0,        ~   ]
TMP_n20cm_syn:        [ -600,             600,            0,        ~   ]
TMP_n50cm_syn:        [ -600,             600,            0,        ~   ]
TMP_n1m_syn:          [ -600,             600,            0,        ~   ]
TMP_n2m_syn:          [ -600,             600,            0,        ~   ]
GH_1000_syn:          [  700,            1070,            0,        ~   ]
PRMSL_ms_syn:         [  920,            1070,            0,        ~   ]
PRMSLNN_ms_met:       [  920,            1070,            0,        ~   ]
WW_syn:               [    0,             293, [508,509,510,511],   "3%"]
WWN_syn:              [    1,               9,            0,        3   ]
W1_syn:               [    0,              19,           31,        3   ]
W2_syn:               [    0,              19,           31,        3   ]
natWW:                [    1,               9,            0,        3   ]
VIS_syn:              [    0,             999,            0,        ~   ]
TCDC_2m_syn:          [    0,               9,            0,        ~   ]
LCDC_2m_syn:          [    0,               0,            0,        ~   ]
MCDC_2m_syn:          [    0,               0,            0,        ~   ]
HCDC_2m_syn:          [    0,               0,            0,        ~   ]
HLC_syn:              [    0,               0,            0,        ~   ]
CLCMCH_syn:           [    0,               0,            0,        ~   ]
CL1_syn:              [    0,               8,            9,        ~   ]
CL2_syn:              [    0,               8,            9,        ~   ]
CL3_syn:              [    0,               8,            9,        ~   ]
CL4_syn:              [    0,               8,            9,        ~   ]
PRATE_1m_syn:         [    0,             999,            0,        ~   ]
  #TR_syn
PCDUR_srf_syn:        [    0,               0,            0,        ~   ]
SNOD_srf_syn:         [    0,               0,            0,        ~   ]
NEWSNOD_srf_syn:      [    0,               0,            0,        ~   ]
GS_syn:               [    0,               0,            0,        ~   ]
SUNDUR_srf_syn:       [    0,               0,           60,        ~   ]
GLRAD_srf_syn:        [    0,               0,            0,        ~   ]
DIFFRAD_srf_syn:      [    0,               0,            0,        ~   ]
LONGRAD_srf_syn:      [    0,               0,            0,        ~   ]
