# WIND SPEED
ms2kn:  &ms2kn  1.9438444924406046  # m/s to kn

meta:
  id_stacji:            location
  stacja:               name
  data_pomiaru:         date
  godzina_pomiaru:      hour

elements:
  temperatura:          [TMP_2m_syn,    1s,   1,     1]
  predkosc_wiatru:      [WIND_10m_syn,  1h, *ms2kn,  0]
  kierunek_wiatru:      [WDIR_10m_syn,  1min, 1,    -1]  
  wilgotnosc_wzgledna:  [RH_2m_syn,     1s,   1,     1] 
  suma_opadu:           [PRATE_1m_syn,  1h,   1,     1]
  cisnienie:            [PRMSL_ms_syn,  1s,   1,     1]
