kn2ms:    &kn2ms    0.51444444444444444 # kn to m/s
0.1kn2ms: &0.1kn2ms 5.14444444444444444 # kn/10 to m/s
metwatch:
# input   : [ amalthea element, duration, multiply by ] # description (from metwatch.cfg documentation)       | units / composition
  IW      : [ sIW,              1h,       ~,          ] # wind unit, not available in BUFR, hardcoded to 4 kn | -
  IX      : [ sIx,              1h,       ~,          ] # ww type, not available in BUFR, hardcoded           | -
  DIR     : [ WDIR_10m_syn,     10min,    ~,          ] # wind direction                                      | degrees
  FF      : [ WIND_10m_syn,     10min,    *kn2ms,     ] # wind speed, 10min average                           | kn -> m/s
  FG      : [ GUST_10m_syn,     TR,       *kn2ms,     ] # wind peak during reference period (TR)              | kn -> m/s
  G1h     : [ GUST_10m_syn,     1h,       *kn2ms,     ] # wind peak during last hour                          | kn -> m/s
  FX      : [ MAXWIND_10m_syn,  TR,       *kn2ms,     ] # maximum 10min average during reference period (TR)  | kn -> m/s
  FFM     : [ WIND_10m_syn,     1h,       *0.1kn2ms,  ] # average wind during last hour                       | kn/10 -> m/s
  TL      : [ TMP_2m_syn,       1s,       0.1,        ] # 2m air temperature                                  | C*10 -> C
  TD      : [ DPT_2m_syn,       1s,       0.1,        ] # 2m dewpoint temperature                             | C*10 -> C
  T5      : [ TMP_5cm_syn,      1s,       0.1,        ] # 5cm air temperature                                 | C*10 -> C
  TX      : [ TMAX_2m_syn,      24h,      0.1,        ] # 24h maximum of 2m air temperature                   | C*10 -> C
  TN      : [ TMIN_2m_syn,      24h,      0.1,        ] # 24h minimum of 2m air temperature                   | C*10 -> C
  TN5     : [ TMIN_5cm_syn,     24h,      0.1,        ] # 24h minimum of 5cm air temperature                  | C*10 -> C
  TW      : [ Twater_sst_syn,   1s,       0.1,        ] # water temperature / sea surface temperature         | C*10 -> C
  Tsfc    : [ TMP_srf_syn,      1s,       0.1,        ] # ground temperature    ~0  cm                        | C*10 -> C
  T-05    : [ TMP_n5cm_syn,     1s,       0.1,        ] # soil temperature      -5  cm                        | C*10 -> C
  T-10    : [ TMP_n10cm_syn,    1s,       0.1,        ] # soil temperature      -10 cm                        | C*10 -> C
  T-20    : [ TMP_n20cm_syn,    1s,       0.1,        ] # soil temperature      -20 cm                        | C*10 -> C
  T-50    : [ TMP_n50cm_syn,    1s,       0.1,        ] # soil temperature      -50 cm                        | C*10 -> C
  T-1m    : [ TMP_n1m_syn,      1s,       0.1,        ] # soil temperature      -1  m                         | C*10 -> C
  T-2m    : [ TMP_n2m_syn,      1s,       0.1,        ] # soil temperature      -2  m                         | C*10 -> C
  QFE     : [ PRES_srf_syn,     1s,       ~,          ] # air pressure at station height (not barometric?)    | hPa
  QFF     : [ PRMSL_ms_syn,     1s,       ~,          ] # air pressure reduced to mean sea level (MSL)        | hPa
  QNH     : [ PRMSL_ms_met,     1s,       ~,          ] # reduced to MSL (according to standard atmosphere)   | hPa
  www     : [ WW_2m_syn,        1h,       ~,          ] # significant weather (SYNOP)                         | ww code (020003)
  MetarWX : [ WW_2m_met,        1h,       ~,          ] # significant weather and cloud status (METAR)        | metar code (020009) ???TODO
  W1      : [ W1_2m_syn,        TR,       ~,          ] # past weather 1                                      | W1 code (020005)
  W2      : [ W2_2m_syn,        TR,       ~,          ] # past weather 2                                      | W2 code (020004)
  WWZ     : [ natWW_2m_syn,     1h,       ~,          ] # additional weather (DWD only)                       | wwz code (020193)
  VIS     : [ VIS_2m_syn,       0s,       ~,          ] # horizontal visibility                               | km
  N       : [ TCDC_2m_syn,      1s,       ~,          ] # cloud cover                                         | octas
  L       : [ LCDC_2m_syn,      1s,       ~,          ] # cloud cover of low or middle clouds                 | octas
  HLC     : [ HLC_2m_syn,       1s,       ~,          ] # height of low clouds                                | m/30 ??? ft ??? synop hh code ???TODO
  ClCmCh  : [ CLCMCH_2m_syn,    1s,       ~,          ] # cloud types in different levels                     | octas + cloud type for all levels
  LAYER1  : [ CL1_2m_syn,       1s,       ~,          ] # lowest cloud level (octas+height)                   | octas + height in m/30
  LAYER2  : [ CL2_2m_syn,       1s,       ~,          ] # 2nd cloud level (octas+height)                      | octas + height in m/30
  LAYER3  : [ CL3_2m_syn,       1s,       ~,          ] # 3rd cloud level (octas+height)                      | octas + height in m/30
  LAYER4  : [ CL4_2m_syn,       1s,       ~,          ] # 4th cloud level (octas+height)                      | octas + height in m/30
  RR      : [ PRATE_1m_syn,     TR,       ~,          ] # precipitation amount during reference period (TR)   | mm | l/m**2
  TR      : [ TR,               ~,        ~,          ] # reference period (TR)                               | synop tr code
  RR1h    : [ PRATE_1m_syn,     1h,       ~,          ] # precipitation amount during last hour               | mm | l/m**2
  hh      : [ PCPDUR_1m_syn,    1h,       ~,          ] # precipitation duration during last hour             | min
  RR24h   : [ PRATE_1m_syn,     24h,      ~,          ] # precipitation amount during last 24hours            | mm | l/m**2
  SNO     : [ SNOD_srf_syn,     1s,       ~,          ] # total snow depth                                    | cm
  NEW     : [ NEWSNOD_srf_syn,  TR,       ~,          ] # new snow depth/amount during reference period (TR)  | cm
  GS      : [ GS_srf_syn,       1min,     ~,          ] # state of ground                                     | state of ground code
  SS24    : [ SUNDUR_srf_syn,   24h,      ~,          ] # sunshine duration of previous day                   | min
  Sh      : [ SUNDUR_srf_syn,   1h,       ~,          ] # sunshine duration of last hour                      | min
  GL1h    : [ GLRAD_srf_syn,    1h,       ~,          ] # global radiation of last hour                       | KJ/m**2/hr
  DF1h    : [ DIFFRAD_srf_syn,  1h,       ~,          ] # diffuse radiation of last hour                      | KW/m**2
  LW1h    : [ LONGRAD_srf_syn,  1h,       ~,          ] # longwave radiation of last hour                     | KW/m**2
