model:
  FP:       integer
  datetime: datetime
  element:  text
  model:    text
  value:    real
  UNIQUE:   (datetime, element, model)

obs_raw:
  dataset:  text NOT NULL # raw tables only!
  file:     int DEFAULT 0 # file ID from file_table (main database)
  datetime: datetime NOT NULL
  duration: text
  element:  text NOT NULL
  value:    text NOT NULL
  cor:      integer DEFAULT 0 #TODO number of corrections (COR/CCA)
  scale:    real DEFAULT NULL
  reduced:  integer DEFAULT 0 #TODO will be set to 1 after handled by "reduce_obs.py"
  UNIQUE:   (dataset, datetime, file, duration, element, cor)

obs_forge:
  datetime: datetime NOT NULL
  duration: text
  element:  text NOT NULL
  value:    text NOT NULL
  UNIQUE:   (datetime, duration, element)

obs_oper:
  datetime: datetime NOT NULL
  duration: text
  element:  text NOT NULL
  value:    text NOT NULL
  UNIQUE:   (datetime, duration, element)

obs_bad:
  dataset:  text NOT NULL
  file:     int DEFAULT 0
  datetime: datetime NOT NULL
  duration: text
  element:  text NOT NULL
  value:    text NOT NULL
  reason:   text NOT NULL
  UNIQUE:   (datetime, duration, element)

#forecast:
