model:
  FP:       integer
  datetime: datetime
  element:  text
  model:    text
  value:    real
  UNIQUE:   (datetime, element, model)

obs:
  datetime: datetime NOT NULL
  duration: text
  element:  text NOT NULL
  value:    text NOT NULL
  exported: integer DEFAULT 0
  UNIQUE:   (datetime, duration, element)
