obs:
  dataset:  text NOT NULL
  file:     int DEFAULT 0 # file ID from file_table (main database)
  datetime: datetime NOT NULL
  duration: text
  element:  text NOT NULL
  value:    text NOT NULL
  cor:      integer DEFAULT 0 #TODO number of corrections (COR/CCA)
  scale:    real DEFAULT NULL
  prio:     int DEFAULT 0
  reduced:  integer DEFAULT 0 #TODO will be set to 1 after handled by "reduce_obs.py"
  UNIQUE:   (datetime, dataset, file, duration, element, cor)
