model:
  FP:       integer
  datetime: integer
  element:  text
  model:    text
  value:    real
  UNIQUE:   (datetime, element, model)

obs:
  dataset:    text NOT NULL
  datetime:   datetime NOT NULL
  timestamp:  integer NOT NULL
  element:    text NOT NULL
  value:      text NOT NULL
  exported:   integer DEFAULT 0
  UNIQUE:     (timestamp, element)

obs_bad:
  dataset:    text NOT NULL
  datetime:   datetime NOT NULL
  #timestamp:  integer NOT NULL
  element:    text NOT NULL
  value:      text NOT NULL
  reason:     text NOT NULL
  #UNIQUE:     (timestamp, element)
  UNIQUE:     (datetime, element)
