020062: # STATE OF THE GROUND (WITH OR WITHOUT SNOW) https://confluence.ecmwf.int/display/ECC/WMO%3D40+code-flag+table#WMO=40codeflagtable-CF_020062
  0:  0
  1:  1
  2:  2
  3:  3
  4:  4
  5:  5
  6:  6
  7:  7
  8:  8
  9:  9
  10: 4
  11: 4
  12: 4
  13: 4
  14: 4
  15: 4
  16: 4
  17: 4
  18: 4
  19: 4
  31: ~

001200: # MREP (Meldung auslösendes Wetterelement)
  0:
  1:
  2:
  3:
  4:  7
  5:
  6:  6
  7:  
  8:  9
  9:
  10:
  11:
  12:
  13:
  14:
  15:
  16:
  17:
  18:
  19:
  20:
  21:
  22:
  23:
  24:
  25:
  26:
  27:
  28:
  29:
  30:
  31:
  32:
  33:
  34:
  35:
  36:
  37:
  38:
  39:
  40:
  41:
  42:
  43:
  44:
  45:
  46:
  47:
  48:
  49:
  50:
  51:
  52:
  53:
  54:
  55:
  56:
  57:
  58:
  59:
  60:
  61:
  62:

#presentWeather https://confluence.ecmwf.int/display/ECC/WMO%3D40+code-flag+table#WMO=40codeflagtable-CF_020003
020003: #TODO associate best as possible with two-digit ww codes (00-99) while skipping the ones we dont use
  0:    0
  1:    1
  2:    2
  3:    3
  4:    4
  5:    5
  6:    6
  7:    7
  8:    8
  9:    9
  10:   10
  11:   11
  12:   12
  13:   13
  14:   14
  15:   15
  16:   16
  17:   17
  18:   18
  19:   19
  20:   20
  21:   21
  22:   22
  23:   23
  24:   24
  25:   25
  26:   26
  27:   27
  28:   28
  29:   29
  30:
  31:
  32:
  33:
  34:
  35:
  36:
  37:
  38:
  39:
  40:   40
  41:   41
  42:   42
  43:   43
  44:   44
  45:   45
  46:   46
  47:   47
  48:   48
  49:   49
  50:   50
  51:   51
  52:   52
  53:   53
  54:   54
  55:   55
  56:   56
  57:   57
  58:   58
  59:   59
  60:   60
  61:   61
  62:   62
  63:   63
  64:   64
  65:   65
  66:   66
  67:   67
  68:   68
  69:   69
  70:   70
  71:   71
  72:   72
  73:   73
  74:   74
  75:   75
  76:   76
  77:   77
  78:   78
  79:   79
  80:   80
  81:   81
  82:   82
  83:   83
  84:   84
  85:   85
  86:   86
  87:   87
  88:   88
  89:   89
  90:   90
  91:   91
  92:   92
  93:   93
  94:   94
  95:   95
  96:   96
  97:   97
  98:   98
  99:   99
  100:  0
  101:  1
  102:  2
  103:  3
  104:  4
  105:  5
  110:  10
  111:  70
  112:  13
  118:  18
  119:
  120:  21
  121:  51
  122:  61
  123:  71
  124:  81
  125:  66
  126:  91
  127:
  128:
  129:
  130:  40
  131:  41
  132:  42
  133:  44
  134:  46
  135:  48
  140:  61
  141:  63
  142:  65
  143:  63
  144:  65
  145:  73
  146:  75
  147:  66
  148:  67
  149:
  150:  50
  151:  51
  152:  52
  153:  53
  154:  54
  155:  55
  156:  56
  157:  57
  158:  58
  159:
  160:  60
  161:  61
  162:  62
  163:  63
  164:  64
  165:  65
  166:  66
  167:  67
  168:  68
  169:
  170:  70
  171:  71
  172:  72
  173:  73
  174:  74
  175:  75
  176:  76
  177:  77
  178:  78
  179:
  180:  80
  181:  81
  182:  82
  183:  83
  184:  84
  185:  85
  186:  86
  187:  87
  188:
  189:  89
  190:  91
  191:  90
  192:  92
  193:  93
  194:  94
  195:  95
  196:  96
  199:  19
  204:
  205:
  206:
  207:
  208:
  209:
  210:
  211:
  212:
  213:
  214:
  215:
  216:
  217:
  218:
  219:
  220:
  221:
  222:
  223:
  224:
  225:
  226:
  227:
  228:
  229:
  230:
  239:
  240:
  241:
  242:
  243:
  244:
  245:
  246:
  247:
  248:
  249:
  250:
  251:
  252:
  253:
  254:
  255:
  256:
  257:
  258:
  259:
  260:
  261:
  262:
  263:
  264:
  265:
  266:
  267:
  268:
  269:
  270:
  271:
  272:
  273:
  274:
  275:
  276:
  277:
  278:
  279:
  280:
  281:
  282:
  283:
  284:
  285:
  286:
  287:
  288:
  289:
  290:
  291:
  292:  90
  293:  90  
  508:  0
  509:  ~
  510:  ~
  511:  0

#pastWeather1 https://confluence.ecmwf.int/display/ECC/WMO%3D35+element+table#WMO=35elementtable-CL_20
020004:
  0:  0
  1:  1
  2:  2
  3:  3
  4:  4
  5:  5
  6:  6
  7:  7
  8:  8
  9:  9
  10: 0
  11: 0
  12: 3
  13: 4
  14: 6
  15: 5
  16: 6
  17: 7
  18: 8
  19: 9
  20:
  21:
  22:
  23:
  24:
  25:
  26:
  27:
  28:
  29:
  30:
  31:

#pastWeather2 https://confluence.ecmwf.int/display/ECC/WMO%3D35+element+table#WMO=35elementtable-CL_20
020005:
  0:  0
  1:  1
  2:  2
  3:  3
  4:  4
  5:  5
  6:  6
  7:  7
  8:  8
  9:  9
  10: 0
  11: 0
  12: 0
  13: 4
  14: 6
  15: 5
  16: 6
  17: 7
  18: 8
  19: 9
  20:
  21:
  22:
  23:
  24:
  25:
  26:
  27:
  28:
  29:
  30:
  31:

020009: # generalWeatherIndicatorTafOrMetar https://confluence.ecmwf.int/display/ECC/WMO%3D40+code-flag+table#WMO=40codeflagtable-CF_020009
  0:  ~     # RESERVED
  1:  NSC   # NSC MIL SIGNIFICANT CLOUD
  2:  CAVOK # CAVOK CLOUD AND VISIBILITY OK
  3:  SKC   # SKC SKY CLEAR
  4:  NSW   # NSW NIL SIGNIFICANT WEATHER
  5:  NCD   # NCD NO CLOUDS DETECTED
  15: ~     # MISSING VALUE

020011: # cloudAmount https://confluence.ecmwf.int/display/ECC/WMO%3D14+code-flag+table#WMO=14codeflagtable-CF_020011
  0:  0
  1:  1
  2:  2
  3:  3
  4:  4
  5:  5
  6:  6
  7:  7
  8:  8
  9:  9
  10: 9
  11: 4 #aufgelockert ? siehe S 26:
  12: 6 #durchbrochen ? https://www.dwd.de/DE/leistungen/lf_11_flugwetterbetriebsdienste/handbuch_flugwetterdienste_ops_4.0_mit_aenderungen.pdf?__blob=publicationFile&v=2
  13: 2 #gering ? FEW = 1-2/8; SCT = 3-4/8: BKN = 5-7/8
  14:
  15:

020203: # formOfPrecipitation (DWD only!)
  0:  0
  1:  0
  2:  0
  3:  0
  4:  
  5:  
  6:  6
  7:  7
  8:  7
  9: 
  10: 0
  11: 6
  12: 7
  13: 7
  14:
  15:
  573440: #TODO is this correct???

020021: # typeOfPrecipitation
  1:
  2:  6
  3:  7
  4:  5
  5:  6
  6:  7
  8:  7
  9:  7
  10: 7
  12: 7
  13: 7
  14: 7
  15:
  16:
  17:
  18:
  19:
  20: 7
  21:
  22:
  23:
  24:
  25:
  26:
  27:
  28:
  29:
  30:

020023: # otherWeatherPhenomena
  1:  3
  2:  ~
  3:  3
  4:  3
  5:  9
  6:  9
  7:  9
  8:  9
  9:  ~
  10: ~
  11: ~
  12: ~
  13: ~
  14: 3
  15:
  16:
  17:
  18:

020025: # reason of obscuration
  1:  4
  2:  4
  3:  4 #Nebelrauchen -> 4???
  4:
  5:
  6:
  7:
  8:
  9:
  10: 3
  11: 3
  12: 3
  13: 7
  14:

020193: #additionalWeatherPhenomena (DWD-only)
  0:    # Nicht belegt
  1:    # Kondensstreifen sich schnell auflösend; Lebensdauer < 1 Minute, bei Vorhandensein oder in der letzten Stunde aufgetreten
  2:    # Kondensstreifen sich langsam auflösend; Lebensdauer 1 bis 14 Minuten, bei Vorhandensein oder in der letzten Stunde aufgetreten
  3:    # Kondensstreifen beständig; Lebensdauer = 15 Minuten, bei Vorhandensein oder in der letzten Stunde aufgetreten
  4:    # Kondensstreifen beständig; Lebensdauer = 15 Minuten, bei Vorhandensein oder in der letzten Stunde aufgetreten
  5:    # Strahlungsreif zur Zeit der Beobachtung
  6:    # Advektionsreif zur Zeit der Beobachtung
  7:    # Raureif zur Zeit der Beobachtung bei erstmaligem Auftreten, danach Meldung nur zu Haupt-und Zwischenterminen
  8:    # Raueis zur Zeit der Beobachtung bei erstmaligem Auftreten, danach Meldung nur zu Haupt-und Zwischenterminen
  9:    # Klareis zur Zeit der Beobachtung bei erstmaligem Auftreten, danach Meldung nur zu Haupt-und Zwischenterminen
  10:   # Nicht belegt
  11:   # Nicht belegt
  12:   # Nicht belegt
  13:   # Nicht belegt
  14:   # Nicht belegt
  15:   # Vorhandensein einer wenigstens teilweise zusammenhängenden Decke aus Schneegriesel zur Zeit der Beobachtung oder vorübergehendes Vorhandensein in der letzten Stunde
  16:   # Vorhandensein einer wenigstens teilweise zusammenhängenden Decke aus Eiskörnern zur Zeit der Beobachtung oder vorübergehendes Vorhandensein in der letzten Stunde
  17:   # Vorhandensein einer wenigstens teilweise zusammenhängenden Decke aus Graupel zur Zeit der Beobachtung oder vorübergehendes Vorhandensein in der letzten Stunde
  18:   # Vorhandensein einer wenigstens teilweise zusammenhängenden Decke aus Hagel zur Zeit der Beobachtung oder vorübergehendes Vorhandensein in der letzten Stunde
  19:   # Nicht belegt
  20:   # Nicht belegt
  21:   # Nicht belegt
  22:   # Nicht belegt
  23: 7 # nach Eiskörnern, wenn die Erscheinung mit dem Deskriptor 0 02 203 (Aktuelles Wetter) nicht beschrieben werden kann
  24:   # nach Glatteisbildung, wenn die Erscheinung mit dem Deskriptor 0 02 203 (Aktuelles Wetter) nicht beschrieben werden kann
  25:   # Nicht belegt
  26:   # Nicht belegt
  27:   # Nicht belegt
  28:   # Nicht belegt
  29:   # Nicht belegt
  30:   # Nicht belegt
  31: 3 # Sandfegen (Sand nicht über Augenhöhe aufgewirbelt), zur Zeit der Beobachtung oder Auftreten in der letzten Stunde
  32: 3 # Sandtreiben (Sand über Augenhöhe aufgewirbelt), zur Zeit der Beobachtung oder Auftreten in der letzten Stunde
  33: 3 # Sandverwehungen, beginnende Verwehungen ab >=5 cm an der Station und/oder auf Verkehrswegen der näheren Umgebung, bei erstmaligem Auftreten oder bei erstmaligem Vorfinden nach Dienstunterbrechung, danach Meldung nur zu Haupt- und Zwischenterminen
  34:   # Nicht belegt
  35:   # Nicht belegt
  36:   # Schneeverwehungen, Verwehungen bei Abweichung >20 cm zur Gesamtschneehöhe an der Station und/oder auf Verkehrswegen der näheren Umgebung, bei erstmaligem Auftretenoder bei erstmaligem Vorfinden nach Dienstunterbrechung, danach Meldung nur zu Haupt-und Zwischenterminen
  37:   # Nicht belegt
  38:   # Nicht belegt
  39:   # Nicht belegt
  40:   # Nicht belegt
  41:   # Nicht belegt
  42:   # Nicht belegt
  43:   # Nicht belegt
  44:   # Nicht belegt
  45: 4 # abgesetzte Nebeltröpfchen (nässender Nebel) bei Auftreten zum Termin
  46:   # Nicht belegt
  47:   # Nicht belegt
  48:   # Nicht belegt
  49:   # Nicht belegt
  50:   # Nicht belegt
  51:   # Nicht belegt
  52:   # Nicht belegt
  53:   # Nicht belegt
  54:   # Nicht belegt
  55:   # Nicht belegt
  56:   # Nicht belegt
  57:   # Nicht belegt
  58:   # Nicht belegt
  59:   # Nicht belegt
  60:   # Nicht belegt
  61:   # Nicht belegt
  62:   # Nicht belegt
  63:   # Nicht belegt
  64:   # Nicht belegt
  65:   # Nicht belegt
  66:   # Nicht belegt
  67:   # Nicht belegt
  68:   # Nicht belegt
  69:   # Nicht belegt
  70: 7 # Industrieschnee, an der Station und/oder auf öffentlichen Verkehrswegen der näheren Umgebung, bei erstmaligem Auftreten oder bei erstmaligem Vorfinden nach Dienstunterbrechung, danach Meldung nur zu Haupt- und Zwischenterminen
  71:   # Reifglätte, an der Station und/oder auf öffentlichen Verkehrswegen der näheren Umgebung, bei erstmaligem Auftreten oder bei erstmaligem Vorfinden nach Dienstunterbrechung, danach Meldung nur zu Haupt- und Zwischenterminen
  72:   # Nicht belegt
  73:   # Nicht belegt
  74:   # Nicht belegt
  75:   # Schneeglätte, an der Station und/oder auf öffentlichen Verkehrswegen der näheren Umgebung, bei erstmaligem Auftreten oder bei erstmaligem Vorfinden nac Dienstunterbrechung, danach Meldung nur zu Haupt- und Zwischenterminen
  76:   # Eisglätte, an der Station und/oder auf öffentlichen Verkehrswegen der näheren Umgebung, bei erstmaligem Auftreten oder bei erstmaligem Vorfinden nach Dienstunterbrechung, danach Meldung nur zu Haupt- und Zwischenterminen
  77:   # Glatteis, an der Station und/oder auf öffentlichen Verkehrswegen der näheren Umgebung, bei erstmaligem Auftreten oder bei erstmaligem Vorfinden nach Dienstunterbrechung, danach Meldung nur zu Haupt- und Zwischenterminen
  78:   # Nicht belegt
  79:   # Nicht belegt
  80:   # Nicht belegt
  81: 7 # gefrierender Regen mit Schauercharakter, wenn die Codeziffern 80, 81 oder 82 mit dem Deskriptor 0 02 203 (Aktuelles Wetter) verschlüsselt wurden und der Niederschlag gefriert
  82:   # Nicht belegt
  83:   # Nicht belegt
  84:   # Nicht belegt
  85:   # Nicht belegt
  86:   # Nicht belegt
  87:   # Nicht belegt
  88:   # Nicht belegt
  89:   # Nicht belegt
  90:   # Nicht belegt
  91:   # Nicht belegt
  92:   # Nicht belegt
  93:   # Nicht belegt
  94:   # Nicht belegt
  95:   # Nicht belegt
  96:   # Nicht belegt
  97:   # Nicht belegt
  98:   # Nicht belegt
  99:   # Böenwalze, bei Vorhandensein zum Termin
  100:  # Nicht belegt
  101:  # Nicht belegt
  102:  # Nicht belegt
  103:  # Nicht belegt
  104:  # Nicht belegt
  105:  # Nicht belegt
  106:  # Nicht belegt
  107:  # Nicht belegt
  108:  # Nicht belegt
  109:  # Nicht belegt
  110:  # Nicht belegt
  111:  # Nicht belegt
  112:  # Nicht belegt
  113:  # Nicht belegt
  114:  # Nicht belegt
  115:  # Nicht belegt
  116:  # Nicht belegt
  117:  # Nicht belegt
  118:  # Nicht belegt
  119:  # Nicht belegt
  120:  # Nicht belegt
  121:  # Nicht belegt
  122:  # Nicht belegt
  123:  # Nicht belegt
  124:  # Nicht belegt
  125:  # Nicht belegt
  126:  # Nicht belegt
  127:  # Keine Angaben

008002: # verticalSignificanceSurfaceObservations https://confluence.ecmwf.int/display/ECC/WMO%3D14+element+table#WMO=14elementtable-CL_8
  0:    0 # Observing rules for base of lowest cloud and cloud types of FM 12 SYNOP and FM 13 SHIP apply
  1:    1 # First non-Cumulonimbus significant layer
  2:    2 # Second non-Cumulonimbus significant layer
  3:    3 # Third non-Cumulonimbus significant layer
  4:    4 # Cumulonimbus layer
  5:    C # Ceiling
  6:    0 # Clouds not detected below the following height(s)
  7:    L # Low cloud
  8:    M # Middle cloud
  9:    H # High cloud
  10:   0 # Cloud layer with base below and top above the station
  11:   0 # Cloud layer with base and top below the station level
  20:   0 # No clouds detected by the cloud detection system
  21:   1 # First instrument detected cloud layer
  22:   2 # Second instrument detected cloud layer
  23:   3 # Third instrument detected cloud layer
  24:   4 # Fourth instrument detected cloud layer
  62:   0 # Value not applicable
  63:   0 # Missing value

020012: # cloudType https://confluence.ecmwf.int/display/ECC/WMO%3D14+element+table#WMO=14elementtable-CL_20
  0:  Ci  # CIRRUS (CI)...............CI
  1:  Cc  # CIRROCUMULUS (CC).........CC
  2:  Cs  # CIRROSTRATUS (CS).........CS
  3:  Ac  # ALTOCUMULUS (AC)..........AC
  4:  As  # ALTOSTRATUS (AS)..........AS
  5:  Ns  # NIMBOSTRATUS (NS).........NS
  6:  Sc  # STRATOCUMULUS(SC).........SC
  7:  St  # STRATUS (ST)..............ST
  8:  Cu  # CUMULUS (CU)..............CU
  9:  Cb  # CUMULONIMBUS (CB).........CB
  10: //  # NO CH CLOUDS
  11: Ci  # CIRRUS FIBRATUS, SOMETIMES UNCINUS, NOT PROGRESSIVELY INADING THE SKY
  12: Ci  # CIRRUS SPISSATUS, IN PATCHES OR ENTANGLED SHEAVES, WHICH USUALLY DO NOT INCREASE AND SOMETIMES SEEM TO BE THE REMAINS OF THE UPPER PART OF AN ANVIL
  13: Ci  # CIRRUS SPISSATUS CUMULONIMBOGENITUS
  14: Ci  # CIRRUS UNCINUS OR FIBRATUS, OR BOTH, PROGRESSIVELY INVADING THE SKY; THEY GENERALLY THICKEN AS A WHOLE
  15: Cs  # CIRRUS (OFTEN IN BANDS) AND CIRROSTRATUS, OR CIRROSTRATUS AL ONE, PROGRESSIVELY INVADING THE SKY; THEY GENERALLY THICKEN AS A WHOLE
  16: Cs  # CIRRUS (OFTEN IN BANDS) AND CIRROSTRATUS, OR CIRROSTRATUS AL ONE, PROGRESSIVELY INVADING THE SKY; THEY GENERALLY THICKEN AS A WHOLE
  17: Cs  # CIRROSTRATUS COVERING THE WHOLE SKY
  18: Cs  # CIRROSTRATUS NOT PROGRESSIVELY INVADING THE SKY AND NOT ENTIRELY COVERING IT
  19: Cc  # CIRROCUMULUS ALONE, OR CIRROCUMULUS PREDOMINANT AMONG THE CH CLOUDS
  20: //  # NO CM CLOUDS
  21: As  # ALTOSTRATUS TRANSLUCIDUS
  22: Ns  # ALTOSTRATUS OPACUS OR NIMBOSTRATUS
  23: Ac  # ALTOCUMULUS TRANSLUCIDUS AT A SINGLE LEVEL
  24: Ac  # PATCHES (OFTEN LENTICULARIS) OF ALTOCUMULUS TRANSLUCIDUS, CONTINUALLY CHANGING AND OCCURING AT ONE OR MORE LEVELS
  25: Ac  # ALTOCUMULUS TRANSLUCIDUS IN BANDS, OR ONE OR MORE LAYERS OF ALTOCUMULUS TRANSLUCIDUS OR OPACUS, PROGRESSIVELY INVADING THE SKY
  26: Ac  # ALTOCUMULUS CUMULOGENITUS (OR CUMULONIMBOGENITUS)
  27: Ac  # ALTOCUMULUS TRANSLUCIDUS OR OPACUS IN TWO OR MORE LAYERS, OR ALTOCUMULUS OPACUS IN A SINGLE LAYER, NOT PROGRESSIVELY INVADING THE SKY
  28: Ac  # ALTOCUMULUS CASTELLANUS OR FLOCUS
  29: Ac  # ALTOCUMULUS OF CHAOTIC SKY, GENERALLY AT SEVERAL LEVELS
  30: //  # NO CL CLOUDS
  31: Cu  # CUMULUS HUMILIS OR CUMULUS FRACTUS OTHER THAN OF BAD WEATHER, OR BOTH
  32: Cu  # CUMULUS MEDIOCRIS OR CONGESTUS, WITH OR WITHOUT CUMULUS OF SPECIES FRACTUS OR HUMULIS OR STRATOCUMULUS, ALL HAVING THEIR BASES AT THE SAME LEVEL
  33: Cb  # CUMULONIMBUS CALVUS, WITH OR WITHOUT CUMULUS, STRATOCUMULUS OR STRATUS
  34: Sc  # STRATOCUMULUS CUMULOGENITUS
  35: Sc  # STRATOCUMULUS OTHER THAN STRATOCUMULUS CUMULOGENITUS
  36: St  # STRATUS NEBULOSUS OR STRATUS FRACTUS OTHER THAN OF BAD WEATH" ER, OR BOTH
  37: Cu  # STRATUS FRACTUS OR CUMULUS FRACTUS OF BAD WEATHER, OR BOTH (PANNUS), USUALLY BELOW ALTOSTRATUS OR NIMBOSTRATUS
  38: Cu  # CUMULUS AND STRATOCUMULUS OTHER THAN STRATOCUMULUS CUMULOGENITUS, WITH BASES AT DIFFERENT LEVELS
  39: Cb  # CUMULONIMBUS CAPILLATUS (OFTEN WITH AN ANVIL), WITH OR WITHOUT CUMULONIMBUS CALVUS, CUMULUS, STRATOCUMULUS, STRATUS OR PANNUS
  59: //
  60: //
  61: //
  62: //
  63: //
