# this file illustrates how to use the !!date, !!dt (datetime) and !!td (timedelta) tags

dat1: !!date  [2024, 4, 25]
dat2: !!date  2024-04-25
dat3: !!date
  year:       "2024"
  month:      "04"
  day:        25
dt1:  !!dt    [2024, 04, 25, 12, 34]
dt2:  !!dt    2024-05-25 12:34
dt3:  !!dt
  year:       2024
  month:      04
  day:        25
  hour:       12
  minute:     "34"
td1:  !!td    [1, 2, 0, 0, 5, 6, 7]
td2:  !!td    {days: 1, seconds: 2, microseconds: 0, milliseconds: 0, minutes: 5, hours: 6, weeks: 7}
td3:  !!td
  days:       1
  seconds:    2
  minutes:    5
  hours:      6
  weeks:      7
td4:  !!td    "7 W 1 day 6 h 5 min 2 s"
